식단 별 운영 시간 데이터를 추가하였습니다.
HipstuCAU/nyam_nyam pull request #34
Opened 2023-03-10 15:43 UTC by TaekH

# 식단별 운영 시간 데이터를 추가하였습니다.
Close #33

### 식단 별 운영시간이 모두 다름에 따라서 시간 데이터를 추가하였습니다.
추가 방식은 아래와 같습니다.
> startDate : 해당 식단의 날짜와 시작 운영시간 데이터입니다.

> endDate: 해당 식단의 날짜와 종료 운영시간 데이터입니다.

따라서 
`startDate : 2023-03-12 11:00:00 +0000`
`endDate : 2023-03-12 12:00:00 +0000` 와 같은 포맷으로 들어가게 됩니다.

### 구현 방식을 설명드리겠습니다.
먼저 json 데이터로 들어오는 식단의 시간 값은 아래와 같습니다.
`"time": "11:00~13:30",`
이 값을 "~" 를 기준으로 파싱하여 들어오는 day값과 조합한 후에 Date 로 변환합니다.
```swift
func getTime(_ time: String, _ date: String) -> [Date] {
        let strTimes = time.components(separatedBy: "~")
        var times: [Date] = []
        for time in strTimes {
            times.append(String("\(date) \(time):00").formatStringToFullDate() ?? Date())
        }
        return times
    }
}
```
변형된 Date 값은 배열로 들어가면서 전달되게 됩니다.
배열의 첫번째 인덱스가 startDate 두번째 인덱스가 endDate 입니다.

### 출력 결과 아래와 같이 Meal 데이터가 구성되는 것을 확인하였습니다.
```
NyamNyam.Meal(mealTime: NyamNyam.MealTime.breakfast, type: NyamNyam.MealType.normal, cafeteria: NyamNyam.Cafeteria.blueMirA, price: "4500", menu: ["빵3종*잼", "시리얼", "소시지*머스타드s", "샐러드", "우유", "과일"], date: 2023-03-11 00:00:00 +0000, status: NyamNyam.Status.normal, startDate: 2023-03-11 08:00:00 +0000, endDate: 2023-03-11 09:00:00 +0000)
```

## + 추가 변경사항
- DummyString 파일을 삭제하였습니다.

2023-03-11 13:40 UTC, feldblume5263 commented on NyamNyam/NyamNyam/Global/Manager/DataManager.swift
> +                                            meals.append(Meal(mealTime: getMealTime(mealTime), type: getMealType(mealType, campus), cafeteria: getCafeteria(cafeteria), price: getPrice(price), menu: g
start Date와 end Date를 현재 index로 접근하는데, data가 없을 경우 out of Range로 문제가 일어날 것 처럼 보여요.
times 배열의 count 등으로 먼저 검사를 한 후 접근해야 할 것 같습니다.

2023-03-11 13:41 UTC, feldblume5263 requested changes
말씀드린 index 부분을 확인해주시면 감사하겠습니다.

2023-03-11 14:20 UTC, TaekH commented on NyamNyam/NyamNyam/Global/Manager/DataManager.swift
> +                                            meals.append(Meal(mealTime: getMealTime(mealTime), type: getMealType(mealType, campus), cafeteria: getCafeteria(cafeteria), price: getPrice(price), menu: g
```
    func getTime(_ time: String, _ date: String) -> [Date] {
        let strTimes = time.components(separatedBy: "~")
        var times: [Date] = []
        for i in 0..<2 {
            times.append(String("\(date) \(strTimes[i]):00").formatStringToFullDate() ?? Date())
        }
        return times
    }
```
함수 내부의 for문 부분을 인덱스로 전달하도록 수정하면 어떨까요 ?
이렇게 수정하면 out of. Range가 일어나지 않을 것 같습니다 !

2023-03-13 06:06 UTC, feldblume5263 commented on NyamNyam/NyamNyam/Global/Manager/DataManager.swift
> +                                            meals.append(Meal(mealTime: getMealTime(mealTime), type: getMealType(mealType, campus), cafeteria: getCafeteria(cafeteria), price: getPrice(price), menu: g
`let strTimes = time.components(separatedBy: "~")` 에서 반드시 time이 "OO ~ OO" 의 형태로 들어온다고 보장할 수 없기 때문에 저렇게 인덱스로 접근하면 위함할 것 같습니다.
strTimes에 index 1이 없을 수도 있어요!

2023-03-13 06:46 UTC, TaekH commented on NyamNyam/NyamNyam/Global/Manager/DataManager.swift
> +                                            meals.append(Meal(mealTime: getMealTime(mealTime), type: getMealType(mealType, campus), cafeteria: getCafeteria(cafeteria), price: getPrice(price), menu: g
확실히 "~"이 없을 수 있겠네요
배열의 크기로 계산해서 2보다 작으면 현재날짜의 00시 00분 00초로 이루어진 배열을 반환하도록 수정해봤습니다 !

```swift
    func getTime(_ time: String, _ date: String) -> [Date] {
        let strTimes = time.components(separatedBy: "~")
        if strTimes.count < 2 {
            return Array(repeating: Calendar.current.date(bySettingHour: 9, minute: 0, second: 0, of: Date()) ?? Date(), count: 2)
        }
        var times: [Date] = []
        for time in strTimes {
            times.append(String("\(date) \(time):00").formatStringToFullDate() ?? Date())
        }
        return times
    }
```

2023-03-13 06:54 UTC, feldblume5263 commented on NyamNyam/NyamNyam/Global/Manager/DataManager.swift
> +                                            meals.append(Meal(mealTime: getMealTime(mealTime), type: getMealType(mealType, campus), cafeteria: getCafeteria(cafeteria), price: getPrice(price), menu: g
네 훨씬 안전해진 것 같아요!
함수가 좀 더 명확한 기능을 하게 만든다면, `func getTime(_ time: String, _ date: String) -> [Date]?` 처럼 `[Date]?` 로 반환하게 해서 문제가 있을 때 nil값을 반환시켜서 저 함수를 사용하는 쪽에서 nil일 때 처리를 해주는 방법도 있을 것 같습니다.

2023-03-13 06:55 UTC, feldblume5263 approved these changes
수고하셨습니다.

2023-03-13 06:57 UTC, TaekH commented on NyamNyam/NyamNyam/Global/Manager/DataManager.swift
> +                                            meals.append(Meal(mealTime: getMealTime(mealTime), type: getMealType(mealType, campus), cafeteria: getCafeteria(cafeteria), price: getPrice(price), menu: g
사용하는 쪽에서 가공을 하니깐 nil일때 처리를 하는 방향이 더 나을 것 같아요 ! 그렇게 수정해보겠습니다 !!

2023-03-13 07:00 UTC, TaekH commented on NyamNyam/NyamNyam/Global/Manager/DataManager.swift
> +                                            meals.append(Meal(mealTime: getMealTime(mealTime), type: getMealType(mealType, campus), cafeteria: getCafeteria(cafeteria), price: getPrice(price), menu: g
[18e2490](https://github.com/HipstuCAU/nyam_nyam/pull/34/commits/18e2490f1fd7f0637443cae94a3c70a544175316) 에서 수정완료입니다 !

2023-03-13 07:00 UTC, merged